// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfnhztqzzlvlflsovdvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmbmh6dHF6emx2bGZsc292ZHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDM5NzIsImV4cCI6MjA2NjE3OTk3Mn0.Iq6H2b_9piDLlZQLm5jyGwgPTfcQbtb4S5I56m7qTNk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);